---
title: "R Notebook"
output: html_notebook
---





```{r}
con <- readRDS("/home/meisl/Workplace/cacoa/data/schizo/con.rds") %>% Conos$new(con) # 

```




```{r}
ctr = c('MB7', 'MB9', 'MB11', 'MB13', 'MB15', 'MB16', 'MB17', 'MB19', 'MB20', 'MB21', 'MB18-2')
scz = c('MB6', 'MB8', 'MB10', 'MB12', 'MB14', 'MB22', 'MB23','MB8-2')
  
anoSample = con$getDatasetPerCell()
fraction=Toch(anoSample)
index=fraction %in% scz

fraction[index]='schizo'
fraction[!index]='control'

table(fraction)

fraction=as.factor(fraction)
```



load cell annotations
```{r}
ano=readRDS("/home/meisl/Workplace/cacoa/data/schizo/tans.rds")
length(ano$high)
length(ano$med)
length(ano$high.clean)
```



```{r}
target.level = 'schizo'
ref.level = 'control'
cao <- Cacoa$new(con, 
                 sample.groups=sample.groups, 
                 cell.groups = ano$high.clean,
                 n.cores=20, target.level=target.level, ref.level=ref.level)
```



```{r, include=FALSE, message=FALSE}
#library(cacoa)
library(conos)
library(ggplot2)
library(dplyr)
library(cowplot)

library(devtools)
library(Matrix)
library(dplyr)
library(magrittr)
library(org.Hs.eg.db)
library(edgeR)

#knitr::opts_chunk$set(fig.width=5, fig.height=3, echo=FALSE, warning=FALSE, message=FALSE)
```

```{r}
cao$plot.theme <- theme_bw(base_size = 16) + 
  theme(plot.title=element_text(hjust = 0.5), 
        legend.background=element_rect(fill=alpha("white", 0.2)),
        legend.text=element_text(size=12), 
        legend.margin=margin(6, 6, 4, 1, 'pt'),
        plot.margin=margin())

alpha <- 0.1; size <- 0.1;

```



# Set example cell subtype

```{r}
# sorted cell type names, with the largest cell types first

example.celltypes <- names(sort(table(cao$cell.groups),decreasing=T))
top1 <- example.celltypes[1]
top2 <- example.celltypes[c(1,2)]

cells.to.contour <- top2
cell.to.go = example.celltypes[3]

alpha <- 0.1; size <- 0.1;

# Set pallet
library(RColorBrewer)
if(length(cao$cell.groups.palette) == 0){
  message('New pallet is set')
  set.seed = 239
  
  qual_col_pals <- brewer.pal.info[brewer.pal.info$category == 'qual',]
  col_vector <- unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))
  cao$cell.groups.palette <- sample(col_vector, length(levels(cao$cell.groups)))
}


```



# Basic visualization

```{r, fig.height=4, fig.width=8, warning=FALSE}
plot_grid(
  cao$plotEmbedding(groups=cao$cell.groups, alpha=alpha, size=size, 
                    title='annotation', plot.na=F, show.legend=FALSE),
  cao$plotEmbedding(groups=fraction, alpha=alpha, size=size, 
                    title='diagnosis', mark.groups=F) + 
    theme(legend.position=c(0.85, 0.15)) +
    guides(color=guide_legend(override.aes = list(size=3,alpha=0.8),title=''))
)
```




# Within-group expression structure and variation

```{r}
cao$estimateExpressionShiftMagnitudes(min.cells=10, n.cells=1e3, dist="cor", n.subsamples=50)
```





```{r fig.width=3,fig.height=4}
cao$plotExpressionDistance(joint=TRUE, notch=TRUE, show.significance=TRUE)
```




```{r fig.width=8, fig.height=4}
cao$plotExpressionDistance(show.significance=TRUE)
```


high resolution 
```{r fig.width=11, fig.height=6}
cao$plotExpressionDistance(show.significance=TRUE)
```



```{r fig.width=5, fig.height=4}
cao$plotExpressionDistanceEmbedding(method='MDS', font.size=2)
```




# Cluster-based compositional

```{r fig.width=8,fig.height=4}
cao$plotCellGroupProportions(alpha=0.3, show.significance=TRUE)
```





## Loadings to the best contrast (bootstrap + resampling)

```{r  warning=FALSE}
cao$estimateCellLoadings()
```

```{r fig.width=12,fig.height=8}

signif.threshold <- 0.05
cao$plotCellLoadings(signif.threshold=signif.threshold, show.pvals=TRUE, alpha=0.01)

cells.signif <- names(cao$test.results$cda$pvals)[cao$test.results$cda$pvals < signif.threshold]
```










# Cluster-free compositional

##Estimate cell density

```{r}
cao$estimateCellDensity()
```

Plot cell density per condition

```{r fig.width=12,fig.height=4}
p0 <- cao$plotEmbedding(groups=cao$cell.groups, alpha=alpha, size=size, 
                        title='annotation', plot.na=FALSE, show.legend=FALSE)
pl <- cao$plotCellDensity(add.points=TRUE, show.grid=TRUE, contours=cells.to.contour)
plot_grid(p0, pl[[ref.level]], pl[[target.level]],  nrow = 1)
```






Differential cell density:

```{r warning=FALSE,message=FALSE}
p1 <- cao$plotDiffCellDensity(method='kde', type='subtract', title='difference',
                              legend.position=c(0,0), contours=cells.to.contour)
p2 <- cao$plotDiffCellDensity(method='kde', type='t.test', title='t.test', 
                              legend.position=c(0,0), contours=cells.to.contour)
p3 <- cao$plotDiffCellDensity(method='kde', type='wilcox', title='wilcox', 
                              legend.position=c(0,0), contours=cells.to.contour)
p4 <- cao$plotDiffCellDensity(method='kde', type='permutation', title='permutation', 
                              legend.position=c(0,0), contours=cells.to.contour,
                              verbose=FALSE)
```



```{r fig.width=7.8,fig.height=8}
plot_grid(p0, p1, p2, p3, nrow=2)
```










